### ISSUE TITLE
get.saved.scripts throws error if there are sourced scripts executed

### ISSUE THREAD

**Issue by ngohoanglankhanh** [End-to-end-provenance/provParseR#24]
![Screen Shot 2019-07-18 at 4 05 27 PM](https://user-images.githubusercontent.com/34677238/61488391-19776180-a976-11e9-9fce-2077241d1aa7.png)
 
Below are the executed scripts:
Test1.R (the script which we collected provenance and run get.saved.scripts)
![Screen Shot 2019-07-18 at 4 08 14 PM](https://user-images.githubusercontent.com/34677238/61488518-6c511900-a976-11e9-9a2d-7c97a9766ac5.png)

Test2.R (the sourced script):
![Screen Shot 2019-07-18 at 4 08 26 PM](https://user-images.githubusercontent.com/34677238/61488574-94407c80-a976-11e9-8b3f-5bfeb71cf733.png)

**Comment by fong22e** [comment]
Fixed in pull request #30 .
